minVersion: "0.13.2"
github:
  owner: getsentry
  repo: sentry-java
changelogPolicy: simple
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: bintray
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-spring"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-spring-boot-starter"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-servlet"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-logback"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-log4j2"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-android"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-android-core"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-android-ndk"
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry-android-timber"
