env:
  global:
    - secure: "Xs3g5ZOMymPp0EvxF0T0tk5xMaV3htMPii5uDS17z9wDWYg7hj78mrP2cFea0ZjIqIjENG7YuxIjw34yb7507pvIxv8v+QvSkwlzVz4XJNzh2w1gbB2C+oVvbmbFd0A2Pmpf3jvkey6Tk5jhW7lxNVAZ7QzONuAf66iWdi6bwSg="
    - secure: "PBz5Jjoaf33a+Iqv5eJsFHbCYP1ZdeiQvrQBH7hJK5/Kdrbn4GCrDx+RkA58ZC8i8ZHfsW2MkMuD7RphcrgHuB3UwcvHwUgrEZaV1/ypIOe5O8CQ4Z0gkHCj2Ei/dsL3fpDU8WuPJSLa13tsMoQTdGaOhluCuSXpuArx3B3gX28="

after_success:
  - "[[ $TRAVIS_BRANCH == 'master' ]] && { python .travis/addServer.py; mvn clean deploy --settings $HOME/.m2/mySettings.xml; };"

matrix:
  include:
#    - language: java
#      dist: precise
#      jdk: oraclejdk7
#      script: env | sort && mvn verify
#      cache:
#        directories:
#          - $HOME/.m2
#    - language: java
#      dist: precise
#      jdk: oraclejdk8
#      script: env | sort && mvn verify
#      cache:
#        directories:
#          - $HOME/.m2
    - language: cpp
      dist: trusty
      jdk: oraclejdk7
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y g++-multilib
      script: env | sort && cd agent && cmake CMakeLists.txt && make && file libsentry_agent.so
      cache: false
      after_success: true
