name: "Check Spotless Formatting"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Check formatting with Spotless
        run: make checkFormat
